package com.ebay.itemeligibility.controller;

import com.ebay.itemeligibility.model.Category;
import com.ebay.itemeligibility.model.WebServiceResponse;
import com.ebay.itemeligibility.service.CategoryService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.RequestBody;

import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import java.util.List;

/**
 *Controller class to add new categories and edit approval status
 */


@Component
@Path("/categories")
public class CategoryController {

    @Autowired
    public CategoryService categoryService;

    /**
     * To Get all the categories set up
     * @return WebServiceResponse All the categories saved in the database
     */


    @GET
    @Path("/getCategories")
    @Produces(MediaType.APPLICATION_JSON)
    public WebServiceResponse<List<Category>>  getItems() {
        return  categoryService.getCategories();
    }

    /**
     * To Save a new category in the database can be used by admins for set up
     * @param category Input category
     * @return WebServiceResponse The autogenerated Id for the saved category
     */
    @POST
    @Path("/saveCategory")
    @Produces(MediaType.APPLICATION_JSON)
    public WebServiceResponse<String> addCategory(@RequestBody Category category) {
        return  categoryService.addCategory(category);
    }

    /**
     * To change the approval for a specified category
     * @param id of the category to change the approval
     * @param preApproved boolean indicating whether to approve or not
     * @return the id of the modified category
     */
    @PUT
    @Path("editApproval/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    public WebServiceResponse<String> approveCategory(@PathParam("id") String id,
                                                      @QueryParam("preApproved") boolean preApproved) {
        return  categoryService.approveCategory(id,preApproved);
    }
}
